<a href="https://colab.research.google.com/github/elintrovertido/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
l = [1,2,3,4,5]
arr = np.array(l)

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
np.__version__

'1.25.2'

In [16]:
x = [[1, 2, 3], [4, 5, 6]]
twod = np.array(x)
print(twod[0,2])
print(twod.ndim)

3
2


In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim

3

In [20]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

In [23]:
arr = np.array(l, dtype = 'S')
arr.dtype

dtype('S1')

In [28]:
l2 = [1.1, 2.1, 3.1]
arr = np.array(l2)
arr = arr.astype('i4')
arr


array([1, 2, 3], dtype=int32)

In [41]:
x = np.array([1,2,3,4,5])
y = x.copy()
x[0] = 12
# y[0] = 42
print(x)
print(y)
y.base

[12  2  3  4  5]
[1 2 3 4 5]


In [42]:
x = np.array([1,2,3,4,5])
y = x.view()
# x[0] = 42
y[0] = 42
print(x)
print(y)

y.base

[42  2  3  4  5]
[42  2  3  4  5]


array([42,  2,  3,  4,  5])

In [47]:
arr = np.array([1,2,3,4,5,6], ndmin = 3)
arr

array([[1, 2, 3, 4, 5, 6]])